### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by mattfelsen** [oherterich/sequencer#1]
I can't get the example to run

**Comment by ghost** [comment]
Have you tried being LESS STUPID?

**Comment by ghost** [comment]
Oh, well now you know my work Git account. Nice!

**Comment by mattfelsen** [comment]
Please update the README

**Comment by ghost** [comment]
Please open a PR and I will review.

**Comment by mattfelsen** [comment]
...you know you can have multiple email addresses (i.e. work & personal) on the same GH account?

**Comment by ghost** [comment]
I know. They just like us to open a separate account.

**Comment by mattfelsen** [comment]
kbye
